// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqvyuaoqsuygmxhqkbbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxdnl1YW9xc3V5Z214aHFrYmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjY3MTMsImV4cCI6MjA2Nzc0MjcxM30.sM8EaTNC3XH5T7V-rtJ1cNR-8w7VLrokctUFjj9CEBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});